# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fp4YGuv9QeFp0XtJy4dl3BnYZ6MxZUQz
"""

import pandas as pd
import numpy as np

df=pd.read_csv("breast-cancer.csv")
actu=df["diagnosis"].map({"M":1,"B":0})
d1=df.iloc[:,0:7]
d1=(d1.drop(columns=['diagnosis',"id"]))
w = np.matrix([[5], [-5], [2], [3], [1]])
d1=np.matrix(d1)
b=-1000
h=np.dot(d1,w)+b
h=sigmod(h)
h = (h >= 0.5).astype(int)
h_df = pd.DataFrame(h, columns=['h'])
result = pd.concat([actu.reset_index(drop=True), h_df], axis=1)

result.columns = ['Actual', 'Predicted']

print(result)